### ISSUE TITLE
Doesn't seem to work on Windows due to shortcuts

### ISSUE THREAD

**Issue by musm** [timholy/Rebugger.jl#14]
I can't get any of the shortcuts to work.

E.g, entering F5 actually enters the `E` character in the Julia prompt. Entering Alt+Shift+Enter also doesn't work to step.  

This is probably a core julia issue not related to Rebugger, but it prevents its usage.

**Comment by timholy** [comment]
Hmm. can you report the result of `read(stdin, Char)` and then hitting the two crucial keys?

Eg: for Alt-Shift-Enter I get
```julia
julia> read(stdin, Char)
^[^[OM
```

and for F5 I get
```julia
julia> read(stdin, Char)
^[[15~
```
Those are a little hard to translate, but I think I can figure it out :smile:.

**Comment by musm** [comment]
Hmm, fresh julia 1.0 repl started from CMD
```
julia> read(stdin,Char)
5
'5': ASCII/Unicode U+0035 (category Nd: Number, decimal digit)
```

I can't hit ALt-Shift-Enter  with reading a single Char since that sets the CMD window into full screen.

**Comment by musm** [comment]
Doing the same from a julia session started from ConEmu gives
```julia
julia> read(stdin,Char)

'\r': ASCII/Unicode U+000d (category Cc: Other, control)

julia>
```

**Comment by musm** [comment]
Both are for F5.

Yep my keyboard has an extra row for the function keys .

**Comment by musm** [comment]
Sorry both give me `'\r': ASCII/Unicode U+000d (category Cc: Other, control)`

**Comment by musm** [comment]
I don't think you can actually use the function keys, at least not in CMD. They seem to correspond to short cuts.  When trying to use them in julia they spit junk.  Hitting alt+shift+enter  just maximize the window.

**Comment by timholy** [comment]
Can you configure your keybindings? "stepin" used to be F11 (which is what some other debuggers use for stepin), but for many people that's "fullscreen." Indeed, I had forgotten that when I first made that choice I had to go to (KDE) Kmenu->System Settings->Shortcuts and disable the F11 key.

This is the second key binding I've chosen and it doesn't work either (see also #15). I am beginning to fear that no matter what I choose, it's not going to work for some people. I think my best hope is to make one set of default choices on Windows, a different one on Linux, and a third on OSX. But with Linux in particular there are so many window managers presumably with different defaults...

Since there's no way I can replicate what you're experiencing, I'm going to need some help from you to determine "who's taking those keybindings" and whether it's configurable. (Just to check, CMD = windows command line?)

**Comment by timholy** [comment]
One more thing, since I'm struggling with Alt-Shift-Enter in another issue can you tell me whether that's working for you? Is it only F5 that's causing you trouble?

**Comment by pfitzseb** [comment]
Alt-Enter is standard for fullscreen in cmd. FWIW neither of the shortcuts work for me in Juno's REPL or powershell either.

Using something like `)` works if adjusted [here](https://github.com/timholy/Rebugger.jl/blob/master/src/ui.jl#L239-L250), but I couldn't figure out any function key or enter keybindings that work on Windows. 

Function keys are indeed [used as shortcuts](http://smallvoid.com/article/winnt-command-prompt-shortcuts.html). Switching the terminal to [`raw mode`](https://github.com/pfitzseb/REPLTreeViews.jl/blob/master/src/utils.jl#L18) allows reading all of those keybindings afaict, but that obviously doesn't help much...

**Comment by timholy** [comment]
OK, it looks like we'll definitely need separate key bindings for Windows, since neither one seems to work now. Does anyone have any suggestions?

**Comment by pfitzseb** [comment]
I kinda like <kbd>Meta-E</kbd> for `stepin` and would like <kbd>Meta-C</kbd> for stacktrace, but there seems to be something wrong with `LineEdit.add_nested_key!` where it klobbers previous nested keybindings or something like that.

Code below works for `stepin` on windows, but I didn't test it anywhere else yet:
```
add_key_stacktrace!(keymap) = nothing # LineEdit.add_nested_key!(keymap, "\x1bc", (s, o...) -> capture_stacktrace(s))

add_key_stepin!(keymap) = LineEdit.add_nested_key!(keymap, "\x1be", (s, o...) -> (stepin(s); enter_rebug(s)))

# These work at the `julia>` prompt and the `rebug>` prompt
const rebugger_modeswitch = Dict{Any,Any}(
    # Alt-C
    # "\x1bc"   => (s, o...) -> capture_stacktrace(s),
    # Alt-E
    "\x1be"   => (s, o...) -> (stepin(s); enter_rebug(s)),
    # Deprecate F11
    "\e[23~"   => (s, o...) -> (stepin(s); rebug_prompt_ref[].repl.header.warnmsg="stepin is now Alt-Shift-Enter"; enter_rebug(s)),
)
```

**Comment by timholy** [comment]
Thanks for the suggestion @pfitzseb! <kbd>Meta-c</kbd> (with a lowercase c) already means [change next word to titlecase](https://docs.julialang.org/en/latest/stdlib/REPL/#Key-bindings-1), but for me <kbd>meta-c</kbd> and <kbd>Meta-C</kbd> (i.e., <kbd> Meta-Shift-c </kbd>) is distinguishable from <kbd>Meta-c</kbd>. True for you (and Juno) too?

<kbd>Meta-e</kbd> seems available. I wonder if we should use <kbd>Meta-Shift-e</kbd> just for consistency? It's also available.

**Comment by pfitzseb** [comment]
<kbd>Meta-Shift-e</kbd> (and similar) don't seem to work for me on Windows (neither in Juno nor in cmd). 

What do you think about <kbd>Meta-e</kbd> (`e` for "Enter Expressions") and <kbd>Meta-s</kbd> (`s` for "stacktrace") instead?

**Comment by timholy** [comment]
I could go with that. I was kind of wondering about saving <kbd> Meta-s </kbd> (or perhaps <kbd> Meta-Shift-s </kbd>) for "save these changes I've made at the REPL back to the file". But that's much less of a priority than simply getting the basic functionality working for most people, so I'm not attached to that idea at all.

**Comment by musm** [comment]
Well there  definitely is a way to capture F5 and other hotkeys in windows.

See 
https://msdn.microsoft.com/en-us/library/windows/desktop/ms646309%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

Example console programs can be found, .i.e
http://www.cplusplus.com/forum/windows/47266/

These seems better suited for another julia module for keyboard interaction / keybindings, although not sure if there is pre existing work here.

**Comment by timholy** [comment]
FWIW nothing has changed with either Revise or Rebugger recently (I haven't had time). Last Rebugger release was Aug 29 and last Revise release was Oct 3. So if this is a recent change it may be due to some other package.

**Comment by musm** [comment]
exactly why it's so strange why it doesn't work anymore. I wonder if  it is due to switching to julia 1.0.1, which might have fixed some repl code that then subtly broke Rebugger on windows...

**Comment by musm** [comment]
I'm hoping at least someone else can confirm before trying to investigate

**Comment by pfitzseb** [comment]
I'm getting
```
julia> show([1,2,3])
[1, 2, 3]
UndefVarError: shbegin not defined while evaluating shbegin
    #= /home/pfitzseb/.julia/packages/Rebugger/tYJpU/src/debug.jl:329 =#
    (Main.Rebugger).stashed[] = (ow, ([1, 2, 3],), (Main.Rebugger).kwstasher(; ))
    #= /home/pfitzseb/.julia/packages/Rebugger/tYJpU/src/debug.jl:330 =#
    throw(Main.Rebugger.StopException())
end
```
in both Windows and Linux when pressing `Meta-E`.

**Comment by timholy** [comment]
It was very helpful to see the backtrace. It seems that point is being credited with an extra two characters: the `sh` is presumably from `show` and `begin` is the beginning of the block. On Linux/REPL I can get the same backtrace if I move point so it's sitting on top of the `o` in `show` before I hit `meta-e`.

Best option would be to insert debugging statements [here](https://github.com/timholy/Rebugger.jl/blob/8f11cb2bc736c0ce981abe2b0ad5dbc52f3418e3/src/debug.jl#L284-L296).

**Comment by pfitzseb** [comment]
Ha, true. Shoulda noticed that, I guess. I'm fairly certain the keybindings are working fine on Windows though.

Unfortunately I'm also getting a new error when the cursor is in the right position:
```
julia> using Revise, Rebugger

julia> using Example

julia> Example.hello("you")
"Hello, you"

The expression for method hello(who::String) in Example at /home/pfitzseb/.julia/packages/Example/kH44X/src/Example.jl:4 was unavailable. Perhaps it was untracked or generated by code.       
```

**Comment by timholy** [comment]
Just to check, you're no longer able to replicate a failure of the key bindings per se, right?

> Unfortunately I'm also getting a new error when the cursor is in the right position:

Hmm, that's surprising:
```julia
julia> using Example
[ Info: Recompiling stale cache file /home/tim/.julia/compiled/v1.0/Example/lLvWP.ji for Example [7876af07-990d-54b4-ab0e-23690620f79a]

julia> hello("you")
"Hello, you"

hello(who::String) in Example at /home/tim/.julia/packages/Example/kH44/src/Example.jl:4
  who = you
rebug> @eval Example let (who,) = Main.Rebugger.getstored("cd25f1a0-dc54-11e8-04c3-137d2d68d070")
       begin
           "Hello, $(who)"
       end
       end
"Hello, you"
```

But it's definitely the case that Revise/Rebugger can't find the expression for everything. I haven't had time recently to track it down. Easiest way to debug is

```julia
julia> m = @which hello("you")
hello(who::String) in Example at /home/tim/.julia/packages/Example/kH44/src/Example.jl:4

julia> Revise.get_def(m)
:(hello(who::String) = begin
          "Hello, $(who)"
      end)
```
and if that fails, track down the error. (The logging macros in `get_def` make it hard to Rebug, but if you comment those out...)

**Comment by pfitzseb** [comment]
Disregard that error, I was on an old version of Rebugger. Things work fine now, except for the keybinding error when the cursor isn't positioned "correctly".

**Comment by timholy** [comment]
OK, so @musm you may be back in the land of "unconfirmed." What exactly happens when you hit the key combinations. Nothing?

**Comment by musm** [comment]
I tried to use 
```
julia> str = read(stdin, String)
```
to help identify what keystrokes are being identified, but it frezes my REPL.

**Comment by timholy** [comment]
Do you hit `Ctrl-D` twice after typing something?

**Comment by musm** [comment]
> Do you hit `Ctrl-D` twice after typing something?

Yes, but it does nothing

![t](https://user-images.githubusercontent.com/4319522/47734763-5c0ad980-dc41-11e8-987d-00a6838163c8.gif)



Apologies, I know I am not providing much, but I just don't know what to provide. From experience the windows julia REPL is buggy, so I wouldn't at all be surprised if this was a julia bug and nothing to do with Rebugger.

**Comment by pfitzseb** [comment]
What's `]st` return? I set up a completley fresh Julia install in a Windows VM and Rebugger works fine there.

**Comment by pfitzseb** [comment]
How are you changing the Julia prompt? Can you try starting Julia without your startup file?

**Comment by musm** [comment]
wow, you hit the nail right on the head

here's my startup file

not using it fixes the problem

```julia
import REPL
import Pkg

atreplinit() do repl
    repl.interface = REPL.setup_interface(repl)
    repl.interface.modes[1].prompt =  () -> begin
        str = Pkg.REPLMode.promptf()
        occursin(r"(v[0-9].[0-9])", str) ? "> " : str[1:end-6] * " > "
    end
end

try
    @eval using BenchmarkTools
catch
    @warn "Could not load BenchmarkTools."
end

# try
#     @eval using Revise
#     # Turn on Revise's file-watching behavior
#     Revise.async_steal_repl_backend()
# catch
#     @warn "Could not load Revise."
# end

# try
#     @eval using Rebugger
#     # Activate Rebugger's key bindings
#     atreplinit(Rebugger.repl_init)
# catch
#     @warn "Could not turn on Rebugger key bindings."
# end

```

**Comment by timholy** [comment]
Great, I think we can close this now. Thanks @pfitzseb!

@musm, Revise has periodically changed its startup recommendations. Latest is https://timholy.github.io/Revise.jl/latest/config.html

**Comment by musm** [comment]
@timholy   

I guess the issue then is that it does not seem possible to utilize `Rebugger` with a custom prompt as defined  below
```
import REPL
import Pkg
atreplinit() do repl
	Rebugger.repl_init

    repl.interface = REPL.setup_interface(repl)
    repl.interface.modes[1].prompt =  () -> begin
        str = Pkg.REPLMode.promptf()
        occursin(r"(v[0-9].[0-9])", str) ? "> " : str[1:end-6] * " > "
    end
end
```

**Comment by timholy** [comment]
Can you file this as a separate issue?
