### ISSUE TITLE
Shift+Alt+Enter step-in keybinding already used by the REPL

### ISSUE THREAD

**Issue by roberthoenig** [timholy/Rebugger.jl#15]
I'm trying to use the new Shift+Alt+Enter keybinding to step into a function. But instead of rebugging the function, the shortcut gets intercepted by the REPL, which inserts a new line.

Even if I'm doing something wrong here and Rebugger actually has keybinding precedence over the REPL, I don't think Rebugger should overwrite an existing keybinding like this.

**Comment by timholy** [comment]
It's Shift-Alt-Enter, not Ctrl-Alt-Enter.

**Comment by timholy** [comment]
>  I don't think Rebugger should overwrite an existing keybinding like this.

For me if I'm not running rebugger and I hit Shift-Alt-Enter repeatedly I get
```julia
julia> OMOMOMOMOMOMOM
```
Doesn't seem to be crucial functionality :smile:.

**Comment by roberthoenig** [comment]
> It's Shift-Alt-Enter, not Ctrl-Alt-Enter.

Whoops, right -- edited the title and issue. I remember trying it Shift+Alt+Enter :) Here is a demo:

![rebugger_shift_alt_enter](https://user-images.githubusercontent.com/7950151/44296995-83503c80-a2c9-11e8-8ff6-c7a677e210b8.gif)

Interesting that you experience a different behavior. Fwiw, I tried Shift+Alt+Enter in a normal terminal session as well, and it didn't do anything, so this doesn't seem to be due to some weird shortcut configuration of my system. But maybe there are other places that interfere?

**Comment by timholy** [comment]
What does
```julia
read(stdin, Char)
```
do when you hit Alt+Shift+Enter?

**Comment by timholy** [comment]
Also can you tell me more about your system. FWIW I'm on Linux/KDE/Kubuntu 18.04.

**Comment by roberthoenig** [comment]
In any case, would you accept a PR for adding a function `setkeybinding(functionality, keybinding)`?

**Comment by timholy** [comment]
Gladly!

**Comment by pfitzseb** [comment]
Just for the record: <kbd>Alt-Shift-Enter</kbd> works fine for me in Konsole (surprise surprise) but doesn't work in Juno's terminal.

**Comment by timholy** [comment]
@roberthoenig I am hoping to officially announce Rebugger on discourse by the end of the weekend. Should I wait for your PR or go ahead without it?

**Comment by roberthoenig** [comment]
I'll try to get up a PR tomorrow. I assume you're in a US timezone, so I'll have even a bit more time ;)
