### ISSUE TITLE
Bad keybindings for Macs?

### ISSUE THREAD

**Issue by timholy** [timholy/Rebugger.jl#28]
At least one user has reported (https://github.com/timholy/Rebugger.jl/pull/21#issuecomment-414836756) that the default keybindings don't work. Anyone else experiencing the same? Can we pick something that does work?

**Comment by timholy** [comment]
For people who want to experiment, see the docs on customization: https://timholy.github.io/Rebugger.jl/stable/config.html#Customize-keybindings-1

**Comment by Jutho** [comment]
@mbauman 's solution works for me!
