### ISSUE TITLE
Rebugger in windows

### ISSUE THREAD

**Issue by cyclesix** [timholy/Rebugger.jl#46]
Thanks for a much needed debugger for Julia 1.0.0.

I try to enter an expression by hovering over the 'a' and pressing Esc+e. I get the following message.

```julia
julia> using Rebugger
julia> abs(2)
Expression at point is not a call expression
rebug> abs(2)
```
The stacktrace (with esc+s) does appear to work fine.

**Comment by timholy** [comment]
When you say "hover over the a" do you mean with the mouse? It has to be with the cursor, i.e., where text would be inserted if you started typing on the keyboard.

**Comment by cyclesix** [comment]
Hi Tim, thanks for the reply. 
Yes, hovering over the 'a' of 'abs' with the mouse cursor. I then press 'esc+e ' and the `jula>` prompt changes to `rebug>` and i get the message `Expression at point is not a call expression`.

**Comment by cyclesix** [comment]
Ah ha, thanks, user error.

**Comment by cyclesix** [comment]
User error no issue with package.
