### ISSUE TITLE
Loading Rebugger only in REPL mode?

### ISSUE THREAD

**Issue by oschulz** [timholy/Rebugger.jl#50]
The Rebugger docs currently don't mention a way to only load Rebugger if Julia is in REPL mode (analog to the `atreplinit() ...` in the Revise docs). I came up with this - it seems to work, but is it safe (without calling `Rebugger.repl_init`, which doesn't seem to work in this setting)?

"startup.jl":

```julia
atreplinit() do repl
    try
        @eval using Revise
        @async Revise.wait_steal_repl_backend()
        @info "Loaded Revise."
    catch
        @warn "Could not load Revise."
    end

    try
        @eval using Rebugger
        Rebugger.keybindings[:stepin] = "\e[17~"      # Add the keybinding F6 to step into a function.
        Rebugger.keybindings[:stacktrace] = "\e[18~"  # Add the keybinding F7 to capture a stacktrace.
        @info "Loaded Rebugger."
    catch
        @warn "Could not load Rebugger."
    end
end
```

**Comment by timholy** [comment]
Hmm, yes, I should have updated those docs. I am a little surprised it's working without `Rebugger.repl_init`, for reference here is my `startup.jl`:

```julia
atreplinit() do repl
    try
        @eval using Revise
        @async Revise.wait_steal_repl_backend()
        @async Revise.debug_logger()
    catch
    end
end

atreplinit() do repl
    try
        @eval using Rebugger
        Rebugger.repl_init()
    catch
    end
end
```

(I turn on the debug logger to make it easier to trap Revise mistakes, not that I've noticed one in a while.)

**Comment by timholy** [comment]
Oh, it looks like `__init__` contains a call to `REPL.setup_interface` too, so I guess it's no longer necessary. Want to submit a PR? Or should I?
