### ISSUE TITLE
Interpret mode fails to show source code when file changes in a method

### ISSUE THREAD

**Issue by KristofferC** [timholy/Rebugger.jl#63]
Function

```jl
function f()
           x = 1 + 1
           @info "hello"
       end
```

Enter interpreted mode and press space a few times

```jl
interpret> f()
f() in Main at REPL[18]:2
  x = 2
  level = Info
  std_level = Info
  group = REPL[18]
  _module = Main
  logger = Logging.ConsoleLogger(Base.TTY(Base.Libc.WindowsRawSocke…ting), Info, Logging.default_metafmt, true, 0, Dict{Any,Int64}())
 1  function f()
 2      x = 1 + 1
<?>
```

**Comment by KristofferC** [comment]
Related, any opinions about changing the condition in https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/901df4d14f56c7794d1643332ec7728cc5700126/src/commands.jl#L181 to `linenumber(frame, pc) == initialline || getfile(frame, pc) != initialfile?

**Comment by timholy** [comment]
I guess it depends on what we mean by `next_line!`; if you mean "the next line of this file" then that would be a bad change to make, `foo(@lookup(a), @lookup(b))` would not work as expected.
