### ISSUE TITLE
Fail to reproduce the tutorial 

### ISSUE THREAD

**Issue by yzcj105** [timholy/Rebugger.jl#74]
This is the info when adding Rebugger.

`(v1.2) pkg> add Revise Rebugger
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.2/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.2/Manifest.toml`
 [no changes]

julia> using Rebugger
[ Info: Recompiling stale cache file /Users//.julia/compiled/v1.2/Rebugger/xlw94.ji for Rebugger [ee283ea6-eecd-56e3-beb3-83eb4d3c31e9]
WARNING: Method definition transition(Function, REPL.LineEdit.PrefixSearchState, Any) in module LineEdit at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:1701 overwritten in module HeaderREPLs at /Users//.julia/packages/HeaderREPLs/xrHVE/src/HeaderREPLs.jl:327.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition deactivate(REPL.LineEdit.TextInterface, REPL.LineEdit.ModeState, Any, REPL.Terminals.TextTerminal) in module LineEdit at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2204 overwritten in module HeaderREPLs at /Users//.julia/packages/HeaderREPLs/xrHVE/src/HeaderREPLs.jl:396.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition activate(REPL.LineEdit.TextInterface, REPL.LineEdit.ModeState, Any, REPL.Terminals.TextTerminal) in module LineEdit at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2209 overwritten in module HeaderREPLs at /Users//.julia/packages/HeaderREPLs/xrHVE/src/HeaderREPLs.jl:382.
  ** incremental compilation may be fatally broken for this module **`

When trying to run 
`a = [ 3,1,2,4]
sort(a) Esc+i`

I got an error

`julia> 
sort(v::AbstractArray{T,1} where T) in Base.Sort at /Applications/Julia-1.2.app/Contents/Resources/julia/share/julia/base/sort.jl:756
  v = [4, 1, 3, 2]
interpret> sort(a)┌ Error: Error in the keymap
│   exception =
│    AssertionError: issorted(skipmissing(linenos))
│    Stacktrace:
│     [1] expression_lines(::Method) at /Users//.julia/packages/Rebugger/nAffk/src/printing.jl:67
│     [2] expression_lines(::JuliaInterpreter.Frame) at /Users//.julia/packages/Rebugger/nAffk/src/printing.jl:135
│     [3] interpret(::REPL.LineEdit.MIState) at /Users//.julia/packages/Rebugger/nAffk/src/ui.jl:214
│     [4] (::getfield(Rebugger, Symbol("##24#27")))(::REPL.LineEdit.MIState, ::HeaderREPLs.HeaderREPL{Rebugger.RebugHeader}, ::Vararg{Any,N} where N) at /Users//.julia/packages/Rebugger/nAffk/src/ui.jl:475
│     [5] #invokelatest#1 at ./essentials.jl:790 [inlined]
│     [6] invokelatest at ./essentials.jl:789 [inlined]
│     [7] (::getfield(REPL.LineEdit, Symbol("##27#28")){getfield(Rebugger, Symbol("##24#27")),String})(::Any, ::Any) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:1356
│     [8] (::getfield(REPL.LineEdit, Symbol("##236#244")))(::Any, ::Any, ::Any) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2172
│     [9] #invokelatest#1 at ./essentials.jl:790 [inlined]
│     [10] invokelatest at ./essentials.jl:789 [inlined]
│     [11] (::getfield(REPL.LineEdit, Symbol("##27#28")){getfield(REPL.LineEdit, Symbol("##236#244")),String})(::Any, ::Any) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:1356
│     [12] prompt!(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2398
│     [13] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2301
│     [14] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:1038
│     [15] run_repl(::REPL.AbstractREPL, ::Any) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:201
│     [16] (::getfield(Base, Symbol("##737#739")){Bool,Bool,Bool,Bool})(::Module) at ./client.jl:390
│     [17] #invokelatest#1 at ./essentials.jl:790 [inlined]
│     [18] invokelatest at ./essentials.jl:789 [inlined]
│     [19] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:374
│     [20] exec_options(::Base.JLOptions) at ./client.jl:312
│     [21] _start() at ./client.jl:464
└ @ REPL.LineEdit /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2400`

**Comment by louisponet** [comment]
The same happens for me on julia v1.3

**Comment by timholy** [comment]
Closed by #76
