### ISSUE TITLE
Status of Rebugger on Julia v1.3?

### ISSUE THREAD

**Issue by oschulz** [timholy/Rebugger.jl#75]
When using Rebugger with Julia v1.3, I always seems to get "Execution did not reach point" when I try to step into an expression, no matter in what function. @timholy, is Rebugger currently incompatible with v1.3? I'm currently preparing a two-day introductory Julia course for end of January, and I was wondering whether to use Rebugger to show some Julia internals.

**Comment by timholy** [comment]
I haven't had time/motivation to maintain it, as I mostly use Juno's debugger now. Will that work for you? I doubt it would take a very long time to update it, but I have been trying to reduce my investment in areas that haven't attracted collaborators.

**Comment by oschulz** [comment]
> I have been trying to reduce my investment in areas that haven't attracted collaborators.

Sure, I understand, there's only so many hours in the day ...

As for Juno - I'm not sure, I've never really used it much. Is Juno's debugger more similar to Rebugger.jl or Debugger.jl?

**Comment by timholy** [comment]
It's a graphical version of Debugger.jl (meaning there are buttons you click, and it takes you automatically to the line in the editor).

**Comment by oschulz** [comment]
I guess what I'm looking for is the convenient navigation in the expression tree that Rebugger provides - I guess that's still kinda unique? But I think I'll manage with Debugger, for a few demos.

**Comment by timholy** [comment]
Yes, that is unique to Rebugger. I should update this sometime, it is still useful.

**Comment by oschulz** [comment]
I really like it when exploring implementations of functions, beats repeated `@less ...` by far! :-)

**Comment by timholy** [comment]
Closed by #76

**Comment by oschulz** [comment]
Thanks, you are my hero, @timholy !
