### ISSUE TITLE
Outdated link in README

### ISSUE THREAD

**Issue by daanhb** [timholy/Rebugger.jl#79]
The link to the keybindings in the readme, at the end of "Installation and usage", seems outdated. It points [here](https://timholy.github.io/Rebugger.jl/latest/config.html#Customize-keybindings-1) but the correct current link seems to be [this one](https://timholy.github.io/Rebugger.jl/dev/#Keyboard-shortcuts-1).

**Comment by timholy** [comment]
Thanks!
